# Generated by Django 6.0.2 on 2026-03-02 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_alter_order_customer_alter_order_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sales.product",
            ),
        ),
    ]
