# Generated by Django 6.0.2 on 2026-03-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_order_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
