# Generated by Django 6.0.2 on 2026-03-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_order_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
