# Generated by Django 6.0.2 on 2026-03-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_order_delivery_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_card_cvv",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_card_exp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_card_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_card_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="card", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_upi_screenshot",
            field=models.ImageField(blank=True, null=True, upload_to="payments/"),
        ),
    ]
