# Generated by Django 6.0.2 on 2026-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_order_payment_card_cvv_order_payment_card_exp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("dress", "Dress"), ("food", "Fruits and Vegetables")],
                default="food",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_or_size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
