# Generated by Django 6.0.2 on 2026-03-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_product_category_product_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_person_mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_person_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
