# Generated by Django 6.0.2 on 2026-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_order_delivery_person_mobile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="cart",
            name="selected_size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="selected_size",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("fruits_veg", "Fruits and Vegetables"),
                    ("snacks", "Snacks"),
                    ("packed_food", "Packed Food"),
                    ("electronics", "Electronics"),
                    ("stationaries", "Stationaries"),
                    ("dairy", "Dairy Items"),
                    ("dress", "Dress"),
                ],
                default="food",
                max_length=20,
            ),
        ),
    ]
