# Generated by Django 6.0.2 on 2026-03-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0014_alter_order_status_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "1 Star - Poor"),
                    (2, "2 Stars - Fair"),
                    (3, "3 Stars - Good"),
                    (4, "4 Stars - Very Good"),
                    (5, "5 Stars - Excellent"),
                ],
                default=5,
            ),
        ),
    ]
