# Generated by Django 6.0.2 on 2026-03-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_alter_review_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
