# Generated by Django 6.0.2 on 2026-03-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_alter_review_review_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_or_size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
