# Generated by Django 6.0.2 on 2026-03-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0017_alter_product_unit_or_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pickup", "Pickup Order"),
                    ("dispatch", "Dispatch"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("return_requested", "Return Requested"),
                    ("returned", "Returned"),
                    ("claim_requested", "Claim Requested"),
                    ("claimed", "Amount Claimed"),
                ],
                default="pickup",
                max_length=30,
            ),
        ),
    ]
